version: "2.4"
services:
  mysql:
    image: mysql:8.0
    container_name: game-mysql
    ports:
      - "3306:3306"
    networks:
      - game-network
    environment:
      - MYSQL_DATABASE=game
      - MYSQL_ROOT_PASSWORD=aaaa8027
      - MYSQL_USER=henry
      - MYSQL_PASSWORD=aaaa8027

  redis:
    image: redis:7.0.1
    container_name: game-redis
    ports:
      - "6379:6379"
    networks:
      - game-network

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: game-zookeeper
    ports:
      - "2181:2181"
    networks:
      - game-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: game-kafka
    ports:
      - "9092:9092"
    networks:
      - game-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: game-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"   # 啟用自動創建主題
      KAFKA_NUM_PARTITIONS: 1                  # 默認分區數
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1      # 默認副本數

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    container_name: kafka-manager
    ports:
      - "9000:9000"
    networks:
      - game-network
    environment:
      ZK_HOSTS: "game-zookeeper:2181" # 指定 Zookeeper 地址
    depends_on:
      - zookeeper
      - kafka

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: game-elasticsearch
    networks:
      - game-network
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: game-kibana
    networks:
      - game-network
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    container_name: game-logstash
    networks:
      - game-network
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  # Beats 輸入
      - "5001:5000/tcp"  # TCP 輸入
      - "5001:5000/udp"  # UDP 輸入
      - "9600:9600"  # Logstash API
networks:
  game-network:
    driver: bridge