// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: proto_data/EnterGroup.proto

package req

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 進入群組(可用於進入直播間)
type EnterGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// group id
	IdP string `protobuf:"bytes,1,opt,name=id_p,json=idP,proto3" json:"id_p,omitempty"`
	// 直播主預設的小游戏 id
	MiniGameIdsArray []int32 `protobuf:"varint,2,rep,packed,name=miniGameIdsArray,proto3" json:"miniGameIdsArray,omitempty"`
	// 透传资料（转抛）
	DataP string `protobuf:"bytes,3,opt,name=data_p,json=dataP,proto3" json:"data_p,omitempty"`
}

func (x *EnterGroup) Reset() {
	*x = EnterGroup{}
	mi := &file_proto_data_EnterGroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGroup) ProtoMessage() {}

func (x *EnterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_EnterGroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGroup.ProtoReflect.Descriptor instead.
func (*EnterGroup) Descriptor() ([]byte, []int) {
	return file_proto_data_EnterGroup_proto_rawDescGZIP(), []int{0}
}

func (x *EnterGroup) GetIdP() string {
	if x != nil {
		return x.IdP
	}
	return ""
}

func (x *EnterGroup) GetMiniGameIdsArray() []int32 {
	if x != nil {
		return x.MiniGameIdsArray
	}
	return nil
}

func (x *EnterGroup) GetDataP() string {
	if x != nil {
		return x.DataP
	}
	return ""
}

var File_proto_data_EnterGroup_proto protoreflect.FileDescriptor

var file_proto_data_EnterGroup_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a,
	0x0a, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x11, 0x0a, 0x04, 0x69,
	0x64, 0x5f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x50, 0x12, 0x2a,
	0x0a, 0x10, 0x6d, 0x69, 0x6e, 0x69, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x73, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x6d, 0x69, 0x6e, 0x69, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x64, 0x73, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61,
	0x50, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2f, 0x72, 0x65, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_data_EnterGroup_proto_rawDescOnce sync.Once
	file_proto_data_EnterGroup_proto_rawDescData = file_proto_data_EnterGroup_proto_rawDesc
)

func file_proto_data_EnterGroup_proto_rawDescGZIP() []byte {
	file_proto_data_EnterGroup_proto_rawDescOnce.Do(func() {
		file_proto_data_EnterGroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_data_EnterGroup_proto_rawDescData)
	})
	return file_proto_data_EnterGroup_proto_rawDescData
}

var file_proto_data_EnterGroup_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_data_EnterGroup_proto_goTypes = []any{
	(*EnterGroup)(nil), // 0: EnterGroup
}
var file_proto_data_EnterGroup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_data_EnterGroup_proto_init() }
func file_proto_data_EnterGroup_proto_init() {
	if File_proto_data_EnterGroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_data_EnterGroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_EnterGroup_proto_goTypes,
		DependencyIndexes: file_proto_data_EnterGroup_proto_depIdxs,
		MessageInfos:      file_proto_data_EnterGroup_proto_msgTypes,
	}.Build()
	File_proto_data_EnterGroup_proto = out.File
	file_proto_data_EnterGroup_proto_rawDesc = nil
	file_proto_data_EnterGroup_proto_goTypes = nil
	file_proto_data_EnterGroup_proto_depIdxs = nil
}
