// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: proto_data/ErrorMessage.proto

package res

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 异常错误码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 提示文案
	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	// 跳转到服务器：服务器ip
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// 跳转到服务器：服务器端口
	Port int32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// 跳转到服务器：服务器游戏类型
	ServerType int32 `protobuf:"varint,5,opt,name=serverType,proto3" json:"serverType,omitempty"`
	// 跳转到服务器：服务器房间类型
	SubType int32 `protobuf:"varint,6,opt,name=subType,proto3" json:"subType,omitempty"`
	// 跳转到服务器：服务器Id
	ServerId int32 `protobuf:"varint,7,opt,name=serverId,proto3" json:"serverId,omitempty"`
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_proto_data_ErrorMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_ErrorMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_data_ErrorMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ErrorMessage) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ErrorMessage) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ErrorMessage) GetServerType() int32 {
	if x != nil {
		return x.ServerType
	}
	return 0
}

func (x *ErrorMessage) GetSubType() int32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *ErrorMessage) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

var File_proto_data_ErrorMessage_proto protoreflect.FileDescriptor

var file_proto_data_ErrorMessage_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb0, 0x01, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73,
	0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x72,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_data_ErrorMessage_proto_rawDescOnce sync.Once
	file_proto_data_ErrorMessage_proto_rawDescData = file_proto_data_ErrorMessage_proto_rawDesc
)

func file_proto_data_ErrorMessage_proto_rawDescGZIP() []byte {
	file_proto_data_ErrorMessage_proto_rawDescOnce.Do(func() {
		file_proto_data_ErrorMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_data_ErrorMessage_proto_rawDescData)
	})
	return file_proto_data_ErrorMessage_proto_rawDescData
}

var file_proto_data_ErrorMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_data_ErrorMessage_proto_goTypes = []any{
	(*ErrorMessage)(nil), // 0: ErrorMessage
}
var file_proto_data_ErrorMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_data_ErrorMessage_proto_init() }
func file_proto_data_ErrorMessage_proto_init() {
	if File_proto_data_ErrorMessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_data_ErrorMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_ErrorMessage_proto_goTypes,
		DependencyIndexes: file_proto_data_ErrorMessage_proto_depIdxs,
		MessageInfos:      file_proto_data_ErrorMessage_proto_msgTypes,
	}.Build()
	File_proto_data_ErrorMessage_proto = out.File
	file_proto_data_ErrorMessage_proto_rawDesc = nil
	file_proto_data_ErrorMessage_proto_goTypes = nil
	file_proto_data_ErrorMessage_proto_depIdxs = nil
}
