// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: proto_data/MyMiniGameBetResult.proto

package req

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 下注结果
type MyMiniGameBetResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 小游戏 ID
	MiniGameId int32 `protobuf:"varint,1,opt,name=miniGameId,proto3" json:"miniGameId,omitempty"`
	// 押注资讯列表
	BetResultInfoListArray []*BetResultInfo `protobuf:"bytes,2,rep,name=betResultInfoListArray,proto3" json:"betResultInfoListArray,omitempty"`
}

func (x *MyMiniGameBetResult) Reset() {
	*x = MyMiniGameBetResult{}
	mi := &file_proto_data_MyMiniGameBetResult_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyMiniGameBetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMiniGameBetResult) ProtoMessage() {}

func (x *MyMiniGameBetResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_MyMiniGameBetResult_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMiniGameBetResult.ProtoReflect.Descriptor instead.
func (*MyMiniGameBetResult) Descriptor() ([]byte, []int) {
	return file_proto_data_MyMiniGameBetResult_proto_rawDescGZIP(), []int{0}
}

func (x *MyMiniGameBetResult) GetMiniGameId() int32 {
	if x != nil {
		return x.MiniGameId
	}
	return 0
}

func (x *MyMiniGameBetResult) GetBetResultInfoListArray() []*BetResultInfo {
	if x != nil {
		return x.BetResultInfoListArray
	}
	return nil
}

// 单个下注结果信息
type BetResultInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 押注信息
	AreaBet *AreaBet `protobuf:"bytes,1,opt,name=areaBet,proto3" json:"areaBet,omitempty"`
	// 下注状态
	Result int32 `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BetResultInfo) Reset() {
	*x = BetResultInfo{}
	mi := &file_proto_data_MyMiniGameBetResult_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetResultInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetResultInfo) ProtoMessage() {}

func (x *BetResultInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_MyMiniGameBetResult_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetResultInfo.ProtoReflect.Descriptor instead.
func (*BetResultInfo) Descriptor() ([]byte, []int) {
	return file_proto_data_MyMiniGameBetResult_proto_rawDescGZIP(), []int{1}
}

func (x *BetResultInfo) GetAreaBet() *AreaBet {
	if x != nil {
		return x.AreaBet
	}
	return nil
}

func (x *BetResultInfo) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 单个押注的具体信息
type AreaBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 注区ID
	AreaCode int32 `protobuf:"varint,1,opt,name=areaCode,proto3" json:"areaCode,omitempty"`
	// 玩家注区总下注金额
	BetScore int32 `protobuf:"varint,2,opt,name=betScore,proto3" json:"betScore,omitempty"`
}

func (x *AreaBet) Reset() {
	*x = AreaBet{}
	mi := &file_proto_data_MyMiniGameBetResult_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaBet) ProtoMessage() {}

func (x *AreaBet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_MyMiniGameBetResult_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaBet.ProtoReflect.Descriptor instead.
func (*AreaBet) Descriptor() ([]byte, []int) {
	return file_proto_data_MyMiniGameBetResult_proto_rawDescGZIP(), []int{2}
}

func (x *AreaBet) GetAreaCode() int32 {
	if x != nil {
		return x.AreaCode
	}
	return 0
}

func (x *AreaBet) GetBetScore() int32 {
	if x != nil {
		return x.BetScore
	}
	return 0
}

var File_proto_data_MyMiniGameBetResult_proto protoreflect.FileDescriptor

var file_proto_data_MyMiniGameBetResult_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x4d, 0x79, 0x4d,
	0x69, 0x6e, 0x69, 0x47, 0x61, 0x6d, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x13, 0x4d, 0x79, 0x4d, 0x69, 0x6e, 0x69,
	0x47, 0x61, 0x6d, 0x65, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x46, 0x0a,
	0x16, 0x62, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x16, 0x62,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x4b, 0x0a, 0x0d, 0x42, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x07, 0x61, 0x72, 0x65, 0x61, 0x42, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x42, 0x65,
	0x74, 0x52, 0x07, 0x61, 0x72, 0x65, 0x61, 0x42, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x41, 0x0a, 0x07, 0x41, 0x72, 0x65, 0x61, 0x42, 0x65, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x61, 0x72, 0x65, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x65, 0x74,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2f, 0x72, 0x65, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_data_MyMiniGameBetResult_proto_rawDescOnce sync.Once
	file_proto_data_MyMiniGameBetResult_proto_rawDescData = file_proto_data_MyMiniGameBetResult_proto_rawDesc
)

func file_proto_data_MyMiniGameBetResult_proto_rawDescGZIP() []byte {
	file_proto_data_MyMiniGameBetResult_proto_rawDescOnce.Do(func() {
		file_proto_data_MyMiniGameBetResult_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_data_MyMiniGameBetResult_proto_rawDescData)
	})
	return file_proto_data_MyMiniGameBetResult_proto_rawDescData
}

var file_proto_data_MyMiniGameBetResult_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_data_MyMiniGameBetResult_proto_goTypes = []any{
	(*MyMiniGameBetResult)(nil), // 0: MyMiniGameBetResult
	(*BetResultInfo)(nil),       // 1: BetResultInfo
	(*AreaBet)(nil),             // 2: AreaBet
}
var file_proto_data_MyMiniGameBetResult_proto_depIdxs = []int32{
	1, // 0: MyMiniGameBetResult.betResultInfoListArray:type_name -> BetResultInfo
	2, // 1: BetResultInfo.areaBet:type_name -> AreaBet
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_data_MyMiniGameBetResult_proto_init() }
func file_proto_data_MyMiniGameBetResult_proto_init() {
	if File_proto_data_MyMiniGameBetResult_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_data_MyMiniGameBetResult_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_MyMiniGameBetResult_proto_goTypes,
		DependencyIndexes: file_proto_data_MyMiniGameBetResult_proto_depIdxs,
		MessageInfos:      file_proto_data_MyMiniGameBetResult_proto_msgTypes,
	}.Build()
	File_proto_data_MyMiniGameBetResult_proto = out.File
	file_proto_data_MyMiniGameBetResult_proto_rawDesc = nil
	file_proto_data_MyMiniGameBetResult_proto_goTypes = nil
	file_proto_data_MyMiniGameBetResult_proto_depIdxs = nil
}
